Map<String, int> category = {
  "General Knowledge": 9,
  "Entertainment: Books ": 10,
  "Entertainment: Films": 11,
  "Entertainment: Music": 12,
  "Entertainment: Musicals and Theatres": 13,
  "Entertainment: Television": 14,
  "Entertainment: Video Games": 15,
  "Entertainment: Board Games": 16,
  "Science & Nature": 17,
  "Science: Computers": 18,
  "Science: Mathematics": 19,
  "Mythology": 20,
  "Sports": 21,
  "Geography": 22,
  "History": 23,
  "Politics": 24,
  "Arts": 25,
  "Celebrity": 26,
  "Animals": 27,
  "Vehicles": 28,
  "Entertainment: Comics": 29,
  "Science: Gadgets": 30,
  "Entertainment: Japanese anime and manga": 31,
  "Entertainment: Cartoon and Animation": 32,
};
